### ISSUE TITLE
Refresh from cover does not refresh the feed in app

### ISSUE THREAD

**Issue by ojhaapala** [florianwittmann/sailgrande#15]
Refreshing from the cover only refreshes the cover.

I usually use the cover refresh and see that there are new pictures - but when I open the appwindow the new images aren't there. I then have manually pull the refresh again.

**Comment by ojhaapala** [comment]
Actually haven't seen this bug after reporting it. Probably just occurs on slow networks?

**Comment by florianwittmann** [comment]
When you refresh from cover and then open the app, it's pulling the images from cache, so this shouldn't make it dependend on network. However, this cache is only valid for a limited time. So you may refreshed the cover already minutes ago and then opened the app, it's getting the images again. This could include some network delays. I close this bug for now, please report if you can reproduce this again.
